before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - binary: repository-settings
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - image_templates:
      - ghcr.io/chrisdoherty4/repository-settings
    goos: linux
    goarch: amd64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
