name: Repository Settings

on:
  push:
    paths-ignore:
      - .github/workflows/test.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # GoReleaser's changelog capability doens't work without git history. A 0 fetch depth
          # ensures we get the entire history.
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          install-only: true

      - name: Build
        run: |
          goreleaser release --rm-dist --snapshot

      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: |
          docker push ghcr.io/chrisdoherty4/repository-settings:latest
